### ISSUE TITLE
can u add docker, docker compose, http, webdav and ftp support?

### ISSUE THREAD

**Issue by aniel300** [nekiwo/DiscordCloudStorage#6]
can u add docker, docker compose, http, webdav and ftp support?

**Comment by nekiwo** [comment]
Unfortunately, due to time constraints I am unable to support this project with any additional features. Feel free to contribute by creating a pull request.

**Comment by aniel300** [comment]
unfortunately idk programing otherwise i would and i thank u for getting back to me.
